Repository Uninett/Argus-frontend, pull requests merged in 2022-10, with the labels that each got.

#380 Display incident end time
  CHANGELOG.md
  NOTES.md
  src/components/incident/IncidentDetails.tsx
  src/components/incident/test/IncidentDetails.test.tsx
Labels: enhancement, usability, size: small

#411 Flip incident events order
  CHANGELOG.md
  NOTES.md
  src/components/incident/IncidentDetails.tsx
Labels: priority: low, size: small

#425 Update changelog with changes implemented before changelog was added
  CHANGELOG.md
  NOTES.md
Labels: documentation, rc-1.8.0, rc-1.6.0

#381 Fix erroneous incident count on rapid table page change
  CHANGELOG.md
  src/components/incidenttable/FilteredIncidentTable.tsx
Labels: bug, priority: high, rc-1.8.0, rc-1.6.0, rr, rc-future

#439 Make phonenumber component prettier
  CHANGELOG.md
  src/components/phonenumber/index.tsx
Labels: rc-1.6.0, rr

#440 Make day select menu stay still
  CHANGELOG.md
  src/components/timeslot/index.tsx
Labels: rc-1.6.0, rr

#397 Add select-all incidents feature
  CHANGELOG.md
  NOTES.md
  src/api/actions.tsx
  src/components/filteredincidentprovider.tsx
  src/components/header/Header.tsx
  src/components/incidentsprovider.tsx
  src/components/incidenttable/FilteredIncidentTable.tsx
  src/components/incidenttable/IncidentTable.tsx
  src/components/incidenttable/IncidentTableToolbar.tsx
  src/components/incidenttable/RealtimeIncidentTable.tsx
  src/state/hooks.tsx
  src/state/reducers/apistate.tsx
  src/views/incident/IncidentView.test.tsx
Labels: enhancement, usability, size: large, rc-1.8.0, rc-1.6.0, rr

#441 Fix enter button not saving/updating telephone number
  CHANGELOG.md
  src/components/phonenumber/index.tsx
Labels: rc-1.6.0, rr

#413 Make phone number optional when creating a notification profile
  CHANGELOG.md
  NOTES.md
  src/components/notificationprofile/NotificationProfileCard.test.tsx
  src/components/notificationprofile/NotificationProfileCard.tsx
  src/components/notificationprofile/NotificationProfileList.tsx
Labels: size: small, notifications, APIv1, APIv2, rc-1.8.0, rc-1.6.0, rr

#446 Remove useless filter list button from the table header
  CHANGELOG.md
  NOTES.md
  src/components/incidenttable/IncidentTableToolbar.tsx
Labels: polish, size: small, rc-1.8.0, rc-1.6.0, rr

#442 Reword "Max level" to "Max severity level"
  CHANGELOG.md
  NOTES.md
  src/components/incident/IncidentFilterToolbar.tsx
Labels: rc-1.6.0, rr

#415 Make timeslots reusable
  CHANGELOG.md
  NOTES.md
  src/api/client.ts
  src/components/notificationprofile/NotificationProfileCard.test.tsx
  src/components/notificationprofile/NotificationProfileCard.tsx
  src/components/notificationprofile/NotificationProfileList.test.tsx
  src/components/notificationprofile/NotificationProfileList.tsx
Labels: usability, notifications, APIv1, rc-1.8.0, rc-1.6.0, rr, rc-future

#444 Use plural words when bulk operating multiple incidents
  CHANGELOG.md
  src/components/incident/CreateAckSignOffAction.tsx
  src/components/incident/IncidentDetails.tsx
  src/components/incident/ManualCloseSignOffAction.tsx
  src/components/incidenttable/IncidentTableToolbar.tsx
Labels: rc-1.6.0, rr
